# Continuous Integration workflow for Fraud Governance API
#
# Triggers:
#   - Push to main/develop branches
#   - Pull requests to main/develop
#
# Jobs:
#   - lint: Code quality checks
#   - test: Unit and smoke tests
#   - test-e2e: E2E integration tests (optional)

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  PYTHON_VERSION: "3.14"
  UV_VERSION: "0.5"

jobs:
  # ============================================================================
  # Linting
  # ============================================================================
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff check
        run: uv run ruff check app tests scripts

      - name: Run ruff format check
        run: uv run ruff format app tests scripts --check

  # ============================================================================
  # Unit & Smoke Tests
  # ============================================================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint

    env:
      DATABASE_URL_APP: ${{ secrets.DATABASE_URL_APP }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run unit tests
        run: uv run pytest -q --tb=short

      - name: Run smoke tests
        run: uv run pytest -m smoke -v --tb=short

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

  # ============================================================================
  # E2E Integration Tests (Manual trigger or main branch only)
  # ============================================================================
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    env:
      DATABASE_URL_APP: ${{ secrets.DATABASE_URL_APP }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run E2E tests
        run: uv run pytest -m e2e_integration -v --tb=short

  # ============================================================================
  # OpenAPI Spec Generation Check
  # ============================================================================
  openapi:
    name: OpenAPI Spec
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Generate OpenAPI spec
        run: uv run python scripts/generate_openapi.py

      - name: Check for uncommitted changes
        run: |
          if git diff --quiet docs/openapi.json; then
            echo "OpenAPI spec is up to date"
          else
            echo "ERROR: OpenAPI spec is out of date. Run 'uv run openapi' and commit."
            git diff docs/openapi.json
            exit 1
          fi
